quarkus:
  # CORS Configuration
  http:
    root-path: /api
    cors:
      enabled: true
      origins: http://localhost:4200
      headers: accept,authorization,content-type,x-requested-with
      methods: GET,POST,PUT,DELETE,OPTIONS
      access-control-allow-credentials: true
  smallrye-openapi:
    store-schema-directory: target
    store-schema-file: openapi.yaml
  # Application
  application:
    name: Library Service

  # Database Configuration
  datasource:
    db-kind: postgresql
    services:
      image-name: postgres:16.3
      db-name: library
    username: libraryuser
    password: librarypass2025
    jdbc:
      url: jdbc:postgresql://localhost:52998/library

  hibernate-orm:
    schema-management:
        strategy: drop-and-create # Use 'update'  if you want to keep data between restarts
    log:
      sql: true